disabled_rules:
    - trailing_whitespace
    - todo
    - shorthand_operator

included:

excluded:
    - Pods
#    - BoostClusteringMaB/AppDelegate.swift
#    - BoostClusteringMaB/SceneDelegate.swift

identifier_name:
  min_length: 1

#large_tuple:
#    - 3

#function_body_length: 200

#line_length:
#    warning: 150
#nesting:
#  type_level: 3
